export const POKEDEX_COPY = {
  badge: 'Pokédex',
  title: 'Pokédex Listing',
  subtitle: 'Browse Pokémon from your backend in a clean, searchable-style grid.',
  pageSummarySuffix: 'Pokémon',
  updatingLabel: 'Updating...',
  loadingTitle: 'Loading Pokémon',
  loadingDescription: 'Fetching Pokédex entries. Please wait a moment.',
  emptyTitle: 'No Pokémon Found',
  emptyDescription: 'The Pokédex is currently empty. Try again later.',
  errorTitle: 'Unable to Load Pokédex',
  errorDescription: 'An unexpected error occurred while loading Pokémon entries.',
  retryButtonLabel: 'Try again',
  filterTypeLabel: 'Type',
  filterNameLabel: 'Name',
  filterOrderLabel: 'Order',
  filterTypePlaceholder: 'e.g. fire',
  filterTypeLoadingPlaceholder: 'Loading types...',
  filterTypeNoResultsLabel: 'No matching types',
  filterNamePlaceholder: 'e.g. charmander',
  filterOrderPlaceholder: 'e.g. 4',
  filterApplyButtonLabel: 'Apply filters',
  filterClearButtonLabel: 'Clear filters',
  numberPrefix: 'Nº',
  fallbackName: 'Unknown Pokémon',
  fallbackStatLabel: 'Pokémon',
  levelLabel: 'Lv.',
  hpLabel: 'HP',
  detailTitleFallback: 'Unknown Pokémon',
  detailSummaryTitle: 'Battle Summary',
  detailDescriptionFallback: 'Detailed battle information for this Pokémon in your Pokédex.',
  detailTypesTitle: 'Type',
  detailStatsTitle: 'Stats',
  detailInfoTitle: 'Info',
  detailBattlesLabel: 'Battles',
  detailWinsLabel: 'Wins',
  detailLossesLabel: 'Losses',
  detailExperienceLabel: 'Experience',
  detailLevelLabel: 'Level',
  detailCurrentHpLabel: 'Current HP',
  detailMaxHpLabel: 'Max HP',
  detailBaseLabel: 'Base',
  detailIvLabel: 'IV',
  detailEvLabel: 'EV',
  detailNoTypesLabel: 'No type information',
  detailLoadingTitle: 'Loading Pokémon Detail',
  detailLoadingDescription: 'Fetching this Pokédex entry. Please wait a moment.',
  detailErrorTitle: 'Unable to Load Detail',
  detailErrorDescription: 'Something went wrong while loading this Pokédex entry.',
  detailEmptyTitle: 'No Detail Found',
  detailEmptyDescription: 'This Pokédex entry could not be found.',
  detailEvolutionsTitle: 'Evolution Chain',
  detailStatHp: 'HP',
  detailStatAttack: 'Attack',
  detailStatDefense: 'Defense',
  detailStatSpAtk: 'Sp. Atk',
  detailStatSpDef: 'Sp. Def',
  detailStatSpeed: 'Speed',
  detailGenderLabel: 'Gender',
};

export const POKEDEX_FALLBACK_IMAGE = '/icon.svg';

