export const HOME_FAKE_TRAINER = {
  id: '9c79fb2e-fcf9-4c7b-ad63-0b4ae17d0e9b',
  name: 'Jorge Machado',
  email: 'jorge.vmachado@gmail.com',
  role: 'USER',
  status: 'ACTIVE',
  gender: 'MALE',
  pokeballs: 5,
  captureRate: 45,
  totalAuthentications: 289,
  authenticationSuccess: 287,
  authenticationFailures: 2,
  createdAt: '2026-03-27T18:11:07.825613',
  updatedAt: '2026-04-09T16:47:49.125326',
  dateOfBirth: '1990-07-20T00:00:00',
  lastAuthenticationAt: '2026-04-09T13:47:49.765955',
  capturedPokemons: [
    { id: 'capt-1', nickname: 'Sparky', pokemonName: 'pikachu', level: 42 },
    { id: 'capt-2', nickname: 'Flare', pokemonName: 'charizard', level: 58 },
    { id: 'capt-3', nickname: 'Shell', pokemonName: 'blastoise', level: 47 },
    { id: 'capt-4', nickname: 'Leaf', pokemonName: 'venusaur', level: 39 },
  ],
  pokedexEntries: [
    { id: 'dex-1', pokemonName: 'pikachu', discovered: true },
    { id: 'dex-2', pokemonName: 'charizard', discovered: true },
    { id: 'dex-3', pokemonName: 'blastoise', discovered: true },
    { id: 'dex-4', pokemonName: 'venusaur', discovered: true },
    { id: 'dex-5', pokemonName: 'mew', discovered: false },
  ],
};

export const HOME_COPY = {
  dashboardLabel: 'Dashboard',
  title: 'Trainer Overview',
  subtitle: 'A clear and elegant snapshot of your trainer profile and battle readiness.',
  fallbackNotice: 'Demo profile loaded while authenticated trainer data is unavailable.',
  metrics: {
    captureRate: 'Capture Rate',
    pokeballs: 'Poke Balls',
    capturedPokemons: 'Captured Pokemons',
    discoveredInPokedex: 'Discovered in Pokedex',
    totalAuthentications: 'Total Authentications',
    successRate: 'Authentication Success Rate',
  },
  topTeam: {
    title: 'Top 3 Highest Level Pokemons',
    empty: 'No captured pokemons available yet.',
  },
  profile: {
    title: 'Trainer Profile',
    id: 'Trainer ID',
    role: 'Role',
    status: 'Status',
    gender: 'Gender',
    email: 'Email',
    dateOfBirth: 'Date of Birth',
  },
  activity: {
    title: 'Authentication Activity',
    success: 'Success',
    failures: 'Failures',
    lastLogin: 'Last Authentication',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
  },
  encounter: {
    title: 'Wild Encounter',
    description: 'Start a wild encounter and decide whether to battle or flee.',
    cta: 'Find Wild Pokemon',
    ctaLoading: 'Searching...',
    modalTitle: 'Wild Pokemon Encountered!',
    modalSubtitle: 'A wild opponent has appeared. What do you want to do?',
    fleeAction: 'Flee',
    battleAction: 'Battle',
  },
  genericWildError: 'Could not find a wild Pokemon now. Try again in a moment.',
};
